version: "3.9"

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./src/:/app

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8083:80
    depends_on:
      - app
    volumes:
      - ./src/:/app

  # swagger:
  #   build:
  #     context: ./docker/swagger
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8084:81
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./swagger/:/app/swagger

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
